name: sit_dbt_elementary
version: "0.1.0"
require-dbt-version: [">=1.0.0", "<2.0.0"]

config-version: 2

profile: local

model-paths: ["models"]
analysis-paths: ["analysis"]
target-path: "target"
clean-targets: ["target"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  sit_dbt_elementary:
    base:
      materialized: table

vars:
  schema: "{{ env_var('DBT_TARGET_SCHEMA') }}"
